name: CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'
    - name: Yarn Install
      run: cd frontend && yarn install
    - name: Build frontend
      run: cd frontend && yarn build
    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        sudo npm install --global firebase-tools
        firebase deploy --token=$FIREBASE_TOKEN --non-interactive
